// Code generated by protoc-gen-go.
// source: cna.proto
// DO NOT EDIT!

/*
Package bmeg is a generated protocol buffer package.

It is generated from these files:
	cna.proto
	genome.proto
	matrix.proto
	ml.proto
	nlp.proto
	obs_deck.proto
	phenotype.proto
	pico.proto
	variant.proto

It has these top-level messages:
	CNACallSet
	CNASegment
	Position
	Gene
	GeneSynonym
	GeneDatabase
	GeneFamily
	GeneExpression
	Cohort
	IndividualCohort
	DoubleVector
	CohortMatrix
	Keyspace
	MatrixVectorEdge
	MatrixAnalysis
	SignatureTraining
	SignatureExpressionEdge
	Pubmed
	HeavilyWeightedGenesSignaturesQuery
	HeavilyWeightedGenesSignaturesResponse
	SampleDataForSamplesWithExtremeScoresQuery
	SampleDataForSamplesWithExtremeScoresResponse
	InferredVariantToSignatureEdgeQuery
	InferredVariantToSignatureEdgesResponse
	SampleGroupDetails
	Quartiles
	AvailableClinicalVarsQuery
	AvailableClinicalVarsResponse
	SampleClinicalDataQuery
	SampleClinicalDataResponse
	AvailableSignaturesQuery
	AvailableSignaturesResponse
	CorrelatorQuery
	DataPagingOptions
	CorrelatorResponse
	ObservationDeckQuery
	ObservationDeckResponse
	SampleSelectionMethod
	SamplePagingOptions
	EventData
	PhenotypeAssociation
	Phenotype
	GeneOntologyTerm
	Evidence
	Compound
	DoseResponse
	ResponseSummary
	ResponseCurve
	List
	Condition
	Fn
	Binding
	Let
	Apply
	Expression
	Domain
	VariantCallEffect
	VariantCall
*/
package bmeg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CNACallSet struct {
	// The call set ID.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The BioSample the call set data was generated from.
	BioSampleId string `protobuf:"bytes,2,opt,name=bio_sample_id" json:"bio_sample_id,omitempty"`
}

func (m *CNACallSet) Reset()                    { *m = CNACallSet{} }
func (m *CNACallSet) String() string            { return proto.CompactTextString(m) }
func (*CNACallSet) ProtoMessage()               {}
func (*CNACallSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CNACallSet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CNACallSet) GetBioSampleId() string {
	if m != nil {
		return m.BioSampleId
	}
	return ""
}

type CNASegment struct {
	ReferenceName string   `protobuf:"bytes,1,opt,name=reference_name" json:"reference_name,omitempty"`
	Start         int64    `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End           int64    `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	Value         float32  `protobuf:"fixed32,4,opt,name=value" json:"value,omitempty"`
	Genes         []string `protobuf:"bytes,5,rep,name=genes" json:"genes,omitempty"`
	CallSetId     string   `protobuf:"bytes,6,opt,name=call_set_id" json:"call_set_id,omitempty"`
}

func (m *CNASegment) Reset()                    { *m = CNASegment{} }
func (m *CNASegment) String() string            { return proto.CompactTextString(m) }
func (*CNASegment) ProtoMessage()               {}
func (*CNASegment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CNASegment) GetReferenceName() string {
	if m != nil {
		return m.ReferenceName
	}
	return ""
}

func (m *CNASegment) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CNASegment) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *CNASegment) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CNASegment) GetGenes() []string {
	if m != nil {
		return m.Genes
	}
	return nil
}

func (m *CNASegment) GetCallSetId() string {
	if m != nil {
		return m.CallSetId
	}
	return ""
}

func init() {
	proto.RegisterType((*CNACallSet)(nil), "bmeg.CNACallSet")
	proto.RegisterType((*CNASegment)(nil), "bmeg.CNASegment")
}

func init() { proto.RegisterFile("cna.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0xc1, 0x8a, 0x83, 0x30,
	0x18, 0x84, 0xd1, 0xa8, 0xe0, 0x2f, 0xee, 0x21, 0xcb, 0x2e, 0x39, 0x8a, 0x27, 0x4f, 0xed, 0xa1,
	0x4f, 0x50, 0xbc, 0xf7, 0xe2, 0x03, 0x84, 0xa8, 0x53, 0x11, 0x92, 0x28, 0x49, 0xda, 0xe7, 0x2f,
	0x09, 0x3d, 0x7e, 0x03, 0xdf, 0xcc, 0x50, 0xbd, 0x58, 0x75, 0x39, 0xdd, 0x11, 0x0e, 0x5e, 0xcc,
	0x06, 0x5b, 0x7f, 0x25, 0x1a, 0x1f, 0xf7, 0x51, 0x69, 0x3d, 0x21, 0x70, 0xa2, 0x7c, 0x5f, 0x45,
	0xd6, 0x65, 0x43, 0xcd, 0xff, 0xa8, 0x9d, 0xf7, 0x43, 0x7a, 0x65, 0x4e, 0x0d, 0xb9, 0xaf, 0x22,
	0x8f, 0x71, 0xef, 0x93, 0x30, 0x61, 0x33, 0xb0, 0x81, 0xff, 0xd3, 0x8f, 0xc3, 0x13, 0x0e, 0x76,
	0x81, 0xb4, 0xca, 0xe0, 0x2b, 0xb7, 0x54, 0xfa, 0xa0, 0x5c, 0x48, 0x12, 0xe3, 0x0d, 0x31, 0xd8,
	0x55, 0xb0, 0x04, 0x2d, 0x95, 0x6f, 0xa5, 0x5f, 0x10, 0x45, 0x97, 0x0d, 0x79, 0xc4, 0x0d, 0x16,
	0x5e, 0x94, 0x1d, 0x1b, 0x6a, 0xfe, 0x4b, 0xcd, 0xa2, 0xb4, 0x96, 0x1e, 0x21, 0x8e, 0x56, 0xb1,
	0x6e, 0xae, 0xd2, 0xe5, 0xdb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x9d, 0xfd, 0xe1, 0xbf, 0x00,
	0x00, 0x00,
}
