// Code generated by protoc-gen-go.
// source: genome.proto
// DO NOT EDIT!

package bmeg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A `Position` is one or more (consecutive***) bases in some `Reference`. A `Position` is
// represented by a `Reference` name, and a base number on that `Reference`
// (0-based).
// ***Modified from GA4GH to include end position.***
type Position struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid  string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	// The name of the `Reference` on which the `Position` is located.
	// (e.g. `chr20` or `X`)
	Chromosome string `protobuf:"bytes,4,opt,name=chromosome" json:"chromosome,omitempty"`
	// The 0-based offset from the start of the forward strand for that
	// `Reference`. Genomic positions are non-negative integers less than
	// `Reference` length.
	//
	// For Variant Calls: The start position at which this variant occurs (0-based).
	// This corresponds to the first base of the string of reference bases.
	// Genomic positions are non-negative integers less than reference length.
	// Variants spanning the join of circular genomes are represented as
	// two variants one on each side of the join (position 0).
	Start int64 `protobuf:"varint,5,opt,name=start" json:"start,omitempty"`
	// The end position (exclusive), resulting in [start, end) closed-open
	// interval.
	//
	// For Variantcalls: This is typically calculated by `start + referenceBases.length`.
	End int64 `protobuf:"varint,6,opt,name=end" json:"end,omitempty"`
	// // Strand the position is associated with.
	// Strand strand = 4;
	Strand string `protobuf:"bytes,7,opt,name=strand" json:"strand,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Position) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Position) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Position) GetChromosome() string {
	if m != nil {
		return m.Chromosome
	}
	return ""
}

func (m *Position) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Position) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Position) GetStrand() string {
	if m != nil {
		return m.Strand
	}
	return ""
}

// Annotation of a contiguous region of a sequence.
// An example might be a gene or a protein.
// For example, a position X might corresponds to gene/Feature TP53.
type Gene struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid         string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Symbol      string `protobuf:"bytes,4,opt,name=symbol" json:"symbol,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Chromosome  string `protobuf:"bytes,6,opt,name=chromosome" json:"chromosome,omitempty"`
	Accession   string `protobuf:"bytes,7,opt,name=accession" json:"accession,omitempty"`
	Refseq      string `protobuf:"bytes,8,opt,name=refseq" json:"refseq,omitempty"`
	// Target: GeneFamily
	InFamily []string `protobuf:"bytes,9,rep,name=inFamily" json:"inFamily,omitempty"`
	// Target: Pubmed
	CitedFrom []string `protobuf:"bytes,10,rep,name=citedFrom" json:"citedFrom,omitempty"`
	// Name/value attributes of the annotation.  Attribute names follow the GFF3
	// naming convention of reserved names starting with an upper cases
	// character, and user-define names start with lower-case.  Most GFF3
	// pre-defined attributes apply, the exceptions are ID and Parent, which are
	// defined as fields. Additional, the following attributes are added:
	// * Score - the GFF3 score column
	// * Phase - the GFF3 phase column for CDS features.
	Info map[string]string `protobuf:"bytes,11,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Gene) Reset()                    { *m = Gene{} }
func (m *Gene) String() string            { return proto.CompactTextString(m) }
func (*Gene) ProtoMessage()               {}
func (*Gene) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Gene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gene) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Gene) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Gene) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Gene) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gene) GetChromosome() string {
	if m != nil {
		return m.Chromosome
	}
	return ""
}

func (m *Gene) GetAccession() string {
	if m != nil {
		return m.Accession
	}
	return ""
}

func (m *Gene) GetRefseq() string {
	if m != nil {
		return m.Refseq
	}
	return ""
}

func (m *Gene) GetInFamily() []string {
	if m != nil {
		return m.InFamily
	}
	return nil
}

func (m *Gene) GetCitedFrom() []string {
	if m != nil {
		return m.CitedFrom
	}
	return nil
}

func (m *Gene) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

type GeneSynonym struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid    string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Symbol string `protobuf:"bytes,4,opt,name=symbol" json:"symbol,omitempty"`
	// Target: Gene
	SynonymFor []string `protobuf:"bytes,5,rep,name=synonymFor" json:"synonymFor,omitempty"`
	// Target: GeneDatabase
	InDatabase []string `protobuf:"bytes,6,rep,name=inDatabase" json:"inDatabase,omitempty"`
}

func (m *GeneSynonym) Reset()                    { *m = GeneSynonym{} }
func (m *GeneSynonym) String() string            { return proto.CompactTextString(m) }
func (*GeneSynonym) ProtoMessage()               {}
func (*GeneSynonym) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GeneSynonym) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneSynonym) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneSynonym) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneSynonym) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GeneSynonym) GetSynonymFor() []string {
	if m != nil {
		return m.SynonymFor
	}
	return nil
}

func (m *GeneSynonym) GetInDatabase() []string {
	if m != nil {
		return m.InDatabase
	}
	return nil
}

type GeneDatabase struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid  string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *GeneDatabase) Reset()                    { *m = GeneDatabase{} }
func (m *GeneDatabase) String() string            { return proto.CompactTextString(m) }
func (*GeneDatabase) ProtoMessage()               {}
func (*GeneDatabase) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GeneDatabase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneDatabase) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneDatabase) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GeneFamily struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid         string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Tag         string `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *GeneFamily) Reset()                    { *m = GeneFamily{} }
func (m *GeneFamily) String() string            { return proto.CompactTextString(m) }
func (*GeneFamily) ProtoMessage()               {}
func (*GeneFamily) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GeneFamily) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneFamily) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneFamily) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneFamily) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GeneFamily) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "bmeg.Position")
	proto.RegisterType((*Gene)(nil), "bmeg.Gene")
	proto.RegisterType((*GeneSynonym)(nil), "bmeg.GeneSynonym")
	proto.RegisterType((*GeneDatabase)(nil), "bmeg.GeneDatabase")
	proto.RegisterType((*GeneFamily)(nil), "bmeg.GeneFamily")
}

func init() { proto.RegisterFile("genome.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x55, 0x9a, 0x8f, 0x36, 0x93, 0x74, 0xb5, 0x9b, 0xdd, 0x83, 0xb5, 0xa7, 0x28, 0xa7, 0x48,
	0x48, 0x39, 0xc0, 0x05, 0x71, 0x05, 0x8a, 0xb8, 0x21, 0x21, 0x7e, 0x80, 0x93, 0x4c, 0x83, 0x45,
	0xec, 0x69, 0x6d, 0x83, 0x94, 0x5f, 0x0f, 0xb2, 0xd3, 0x72, 0xe0, 0x80, 0x2a, 0x8e, 0x6f, 0xe4,
	0xf7, 0xde, 0xbc, 0x37, 0x86, 0x7c, 0x40, 0x45, 0x12, 0x9b, 0x9d, 0x26, 0x4b, 0x45, 0xd4, 0x4a,
	0x1c, 0xaa, 0x3d, 0xac, 0x1e, 0xc8, 0x08, 0x2b, 0x48, 0x15, 0x00, 0x0b, 0xd1, 0xb3, 0xa0, 0x0c,
	0xea, 0xb4, 0xc8, 0x20, 0x1c, 0x44, 0xcf, 0x16, 0x1e, 0xe4, 0x10, 0xd9, 0x69, 0x87, 0x2c, 0xf4,
	0xa8, 0x00, 0xe8, 0x9e, 0x35, 0x49, 0x32, 0x24, 0x91, 0x45, 0x7e, 0xb6, 0x86, 0xd8, 0x58, 0xae,
	0x2d, 0x8b, 0xcb, 0xa0, 0x0e, 0x1d, 0x1b, 0x55, 0xcf, 0x12, 0x0f, 0x7e, 0x41, 0x62, 0xac, 0xe6,
	0xaa, 0x67, 0x4b, 0xf7, 0xb6, 0x7a, 0x0f, 0x20, 0xba, 0x43, 0x85, 0xa7, 0xfa, 0x39, 0xfe, 0x24,
	0x5b, 0x1a, 0x0f, 0x5e, 0x7f, 0x21, 0xeb, 0xd1, 0x74, 0x5a, 0xec, 0xdc, 0xd6, 0xde, 0xf1, 0xeb,
	0x52, 0x89, 0x9f, 0xfd, 0x81, 0x94, 0x77, 0x1d, 0x1a, 0xe3, 0x9e, 0x2d, 0x8f, 0x5a, 0x1a, 0xb7,
	0x06, 0xf7, 0x6c, 0xe5, 0xf1, 0x6f, 0x58, 0x09, 0xb5, 0xe1, 0x52, 0x8c, 0x13, 0x4b, 0xcb, 0x70,
	0x26, 0x75, 0xc2, 0x62, 0xbf, 0xd1, 0x24, 0x19, 0xf8, 0x51, 0x05, 0x91, 0x50, 0x5b, 0x62, 0x59,
	0x19, 0xd6, 0xd9, 0xf9, 0xbf, 0xc6, 0x15, 0xd7, 0xb8, 0x04, 0xcd, 0xbd, 0xda, 0xd2, 0xad, 0xb2,
	0x7a, 0xfa, 0x7f, 0x06, 0xe9, 0x27, 0x70, 0x61, 0x5e, 0x70, 0x3a, 0x24, 0x5b, 0x43, 0xfc, 0xc6,
	0xc7, 0x57, 0x9c, 0xb3, 0x5d, 0x2d, 0x2e, 0x83, 0x6a, 0x84, 0xcc, 0xd1, 0x1f, 0x27, 0x45, 0x6a,
	0x92, 0x3f, 0xed, 0xa1, 0x00, 0x30, 0xb3, 0xc2, 0x86, 0x34, 0x8b, 0xfd, 0xaa, 0x05, 0x80, 0x50,
	0x37, 0xdc, 0xf2, 0x96, 0x1b, 0x57, 0x43, 0x58, 0xa7, 0xd5, 0x35, 0xe4, 0xce, 0xed, 0x38, 0x3d,
	0xd5, 0x2e, 0x87, 0x48, 0xf1, 0xe3, 0x81, 0xab, 0x27, 0x00, 0x27, 0x32, 0x57, 0x75, 0xaa, 0x44,
	0x06, 0xa1, 0xe5, 0xc3, 0x37, 0x67, 0x6b, 0x13, 0xff, 0x17, 0x2f, 0x3e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x98, 0xaa, 0x0b, 0x8d, 0x9b, 0x02, 0x00, 0x00,
}
