# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='bmeg',
  syntax='proto3',
  serialized_pb=b'\n\x08ml.proto\x12\x04\x62meg\"\xba\x02\n\x0fLinearSignature\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cpredictor_id\x18\x02 \x01(\t\x12\x10\n\x08quantile\x18\x03 \x03(\x01\x12\x11\n\tintercept\x18\x04 \x01(\x01\x12=\n\x0c\x63oefficients\x18\x05 \x03(\x0b\x32\'.bmeg.LinearSignature.CoefficientsEntry\x12\x39\n\nbackground\x18\x06 \x03(\x0b\x32%.bmeg.LinearSignature.BackgroundEntry\x1a\x33\n\x11\x43oefficientsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x31\n\x0f\x42\x61\x63kgroundEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LINEARSIGNATURE_COEFFICIENTSENTRY = _descriptor.Descriptor(
  name='CoefficientsEntry',
  full_name='bmeg.LinearSignature.CoefficientsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bmeg.LinearSignature.CoefficientsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='bmeg.LinearSignature.CoefficientsEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=282,
)

_LINEARSIGNATURE_BACKGROUNDENTRY = _descriptor.Descriptor(
  name='BackgroundEntry',
  full_name='bmeg.LinearSignature.BackgroundEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bmeg.LinearSignature.BackgroundEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='bmeg.LinearSignature.BackgroundEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=333,
)

_LINEARSIGNATURE = _descriptor.Descriptor(
  name='LinearSignature',
  full_name='bmeg.LinearSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bmeg.LinearSignature.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictor_id', full_name='bmeg.LinearSignature.predictor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantile', full_name='bmeg.LinearSignature.quantile', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intercept', full_name='bmeg.LinearSignature.intercept', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coefficients', full_name='bmeg.LinearSignature.coefficients', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='background', full_name='bmeg.LinearSignature.background', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LINEARSIGNATURE_COEFFICIENTSENTRY, _LINEARSIGNATURE_BACKGROUNDENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=333,
)

_LINEARSIGNATURE_COEFFICIENTSENTRY.containing_type = _LINEARSIGNATURE
_LINEARSIGNATURE_BACKGROUNDENTRY.containing_type = _LINEARSIGNATURE
_LINEARSIGNATURE.fields_by_name['coefficients'].message_type = _LINEARSIGNATURE_COEFFICIENTSENTRY
_LINEARSIGNATURE.fields_by_name['background'].message_type = _LINEARSIGNATURE_BACKGROUNDENTRY
DESCRIPTOR.message_types_by_name['LinearSignature'] = _LINEARSIGNATURE

LinearSignature = _reflection.GeneratedProtocolMessageType('LinearSignature', (_message.Message,), dict(

  CoefficientsEntry = _reflection.GeneratedProtocolMessageType('CoefficientsEntry', (_message.Message,), dict(
    DESCRIPTOR = _LINEARSIGNATURE_COEFFICIENTSENTRY,
    __module__ = 'ml_pb2'
    # @@protoc_insertion_point(class_scope:bmeg.LinearSignature.CoefficientsEntry)
    ))
  ,

  BackgroundEntry = _reflection.GeneratedProtocolMessageType('BackgroundEntry', (_message.Message,), dict(
    DESCRIPTOR = _LINEARSIGNATURE_BACKGROUNDENTRY,
    __module__ = 'ml_pb2'
    # @@protoc_insertion_point(class_scope:bmeg.LinearSignature.BackgroundEntry)
    ))
  ,
  DESCRIPTOR = _LINEARSIGNATURE,
  __module__ = 'ml_pb2'
  # @@protoc_insertion_point(class_scope:bmeg.LinearSignature)
  ))
_sym_db.RegisterMessage(LinearSignature)
_sym_db.RegisterMessage(LinearSignature.CoefficientsEntry)
_sym_db.RegisterMessage(LinearSignature.BackgroundEntry)


_LINEARSIGNATURE_COEFFICIENTSENTRY.has_options = True
_LINEARSIGNATURE_COEFFICIENTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001')
_LINEARSIGNATURE_BACKGROUNDENTRY.has_options = True
_LINEARSIGNATURE_BACKGROUNDENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001')
# @@protoc_insertion_point(module_scope)
